"""联盟类型常量定义。

此模块定义了 Warcraft 3 JASS 中的联盟类型常量，
与 common.j 中的定义保持一致。
"""

# 联盟类型常量
ALLIANCE_PASSIVE = 0
ALLIANCE_HELP_REQUEST = 1
ALLIANCE_HELP_RESPONSE = 2
ALLIANCE_SHARED_XP = 3
ALLIANCE_SHARED_SPELLS = 4
ALLIANCE_SHARED_VISION = 5
ALLIANCE_SHARED_CONTROL = 6
ALLIANCE_SHARED_ADVANCED_CONTROL = 7
ALLIANCE_RESCUABLE = 8
ALLIANCE_SHARED_VISION_FORCED = 9

# 联盟类型名称映射（用于日志输出）
ALLIANCE_NAMES = {
    ALLIANCE_PASSIVE: "ALLIANCE_PASSIVE",
    ALLIANCE_HELP_REQUEST: "ALLIANCE_HELP_REQUEST",
    ALLIANCE_HELP_RESPONSE: "ALLIANCE_HELP_RESPONSE",
    ALLIANCE_SHARED_XP: "ALLIANCE_SHARED_XP",
    ALLIANCE_SHARED_SPELLS: "ALLIANCE_SHARED_SPELLS",
    ALLIANCE_SHARED_VISION: "ALLIANCE_SHARED_VISION",
    ALLIANCE_SHARED_CONTROL: "ALLIANCE_SHARED_CONTROL",
    ALLIANCE_SHARED_ADVANCED_CONTROL: "ALLIANCE_SHARED_ADVANCED_CONTROL",
    ALLIANCE_RESCUABLE: "ALLIANCE_RESCUABLE",
    ALLIANCE_SHARED_VISION_FORCED: "ALLIANCE_SHARED_VISION_FORCED",
}


def get_alliance_name(alliance_type: int) -> str:
    """获取联盟类型的名称。

    参数：
        alliance_type: 联盟类型整数

    返回：
        联盟类型的可读名称，如果未知则返回 "UNKNOWN"
    """
    return ALLIANCE_NAMES.get(alliance_type, f"UNKNOWN({alliance_type})")
